/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defencesystem.view;

import defencesystem.controller.DefenceObservable;
import defencesystem.controller.DefenceObserver;
import defencesystem.Strength;
import defencesystem.SuperDefence;
import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Naveen Chathurya
 */
public class Submarine extends SuperDefence implements DefenceObserver {
    
    private static DefenceObserver submarine;
    private Strength strength = Strength.LOW;
    private DefenceObservable defenceObservable = DefenceObservable.getInstance();
    
    public static DefenceObserver getInstance() {
        if(submarine==null)
            submarine = new Submarine();
        return submarine;
    }

    private Submarine() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
        btnMarineShoot.setEnabled(false);
        btnMarineSonar.setEnabled(false);
        btnMarineTomahawk.setEnabled(false);
        btnMarineTrident.setEnabled(false);
        txtAreaMarine.setEditable(false);
        txtAreaMarine.setEnabled(false);
        setResizable(false);
        setLayout(null);
        setBounds(980, 30, 720, 500);
        getContentPane().setBackground(new Color(234,236,233)); 
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sliderMarineEnergy = new javax.swing.JSlider();
        lblMarineArea = new javax.swing.JLabel();
        btnMarineSonar = new javax.swing.JButton();
        btnMarineShoot = new javax.swing.JButton();
        btnMarineTomahawk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMarine = new javax.swing.JTextArea();
        txtFieldMarine = new javax.swing.JTextField();
        btnMarineSend = new javax.swing.JButton();
        lblMarineSoldier = new javax.swing.JLabel();
        lblMarineAmmo = new javax.swing.JLabel();
        spinnerMarineSoldier = new javax.swing.JSpinner();
        spinnerMarineAmmo = new javax.swing.JSpinner();
        chkBoxMarinePosition = new javax.swing.JCheckBox();
        btnMarineTrident = new javax.swing.JButton();
        sliderMarineOxygen = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Submarine");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sliderMarineEnergy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sliderMarineEnergy.setMajorTickSpacing(20);
        sliderMarineEnergy.setMinorTickSpacing(10);
        sliderMarineEnergy.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderMarineEnergy.setPaintLabels(true);
        sliderMarineEnergy.setPaintTicks(true);
        sliderMarineEnergy.setValue(0);

        lblMarineArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMarineArea.setText("Area Not Cleared");

        btnMarineSonar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarineSonar.setText("Sonar Operation");

        btnMarineShoot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarineShoot.setText("Shoot");

        btnMarineTomahawk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarineTomahawk.setText("Tomahawk Missile");

        txtAreaMarine.setColumns(20);
        txtAreaMarine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAreaMarine.setRows(5);
        txtAreaMarine.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(txtAreaMarine);

        txtFieldMarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldMarineActionPerformed(evt);
            }
        });
        txtFieldMarine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldMarineKeyPressed(evt);
            }
        });

        btnMarineSend.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarineSend.setText("Send");
        btnMarineSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarineSendActionPerformed(evt);
            }
        });

        lblMarineSoldier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMarineSoldier.setText("Soldier Count");

        lblMarineAmmo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMarineAmmo.setText("Ammo Count");

        chkBoxMarinePosition.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkBoxMarinePosition.setText("Position");
        chkBoxMarinePosition.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkBoxMarinePositionStateChanged(evt);
            }
        });
        chkBoxMarinePosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxMarinePositionActionPerformed(evt);
            }
        });

        btnMarineTrident.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMarineTrident.setText("Trident-2 Missile");

        sliderMarineOxygen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sliderMarineOxygen.setMajorTickSpacing(20);
        sliderMarineOxygen.setMinorTickSpacing(10);
        sliderMarineOxygen.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderMarineOxygen.setPaintLabels(true);
        sliderMarineOxygen.setPaintTicks(true);
        sliderMarineOxygen.setValue(0);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Energy");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Oxygen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMarineArea, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtFieldMarine, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnMarineSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnMarineTomahawk, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnMarineTrident, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnMarineShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnMarineSonar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chkBoxMarinePosition)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMarineAmmo)
                                        .addComponent(lblMarineSoldier))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spinnerMarineSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spinnerMarineAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderMarineEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(sliderMarineOxygen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMarineArea, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnMarineSonar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMarineShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkBoxMarinePosition, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnMarineTrident, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMarineTomahawk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMarineSoldier)
                                    .addComponent(spinnerMarineSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMarineAmmo)
                                    .addComponent(spinnerMarineAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMarineSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFieldMarine)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sliderMarineOxygen, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sliderMarineEnergy, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkBoxMarinePositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxMarinePositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxMarinePositionActionPerformed

    private void txtFieldMarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldMarineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldMarineActionPerformed

    private void btnMarineSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarineSendActionPerformed
        // TODO add your handling code here:
        defenceObservable.setCountsSub((int)spinnerMarineSoldier.getValue(),(int)spinnerMarineAmmo.getValue());
    }//GEN-LAST:event_btnMarineSendActionPerformed

    private void txtFieldMarineKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldMarineKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            defenceObservable.recieveMessageSub("Submarine : "+txtFieldMarine.getText()); 
            txtFieldMarine.setText("");
        }
    }//GEN-LAST:event_txtFieldMarineKeyPressed

    private void chkBoxMarinePositionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkBoxMarinePositionStateChanged
        if(chkBoxMarinePosition.isSelected()) {
            position(strength);
        }else {
            btnMarineShoot.setEnabled(false);
            btnMarineSonar.setEnabled(false);
            btnMarineTomahawk.setEnabled(false);
            btnMarineTrident.setEnabled(false);
        }
    }//GEN-LAST:event_chkBoxMarinePositionStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarineSend;
    private javax.swing.JButton btnMarineShoot;
    private javax.swing.JButton btnMarineSonar;
    private javax.swing.JButton btnMarineTomahawk;
    private javax.swing.JButton btnMarineTrident;
    private javax.swing.JCheckBox chkBoxMarinePosition;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMarineAmmo;
    private javax.swing.JLabel lblMarineArea;
    private javax.swing.JLabel lblMarineSoldier;
    private javax.swing.JSlider sliderMarineEnergy;
    private javax.swing.JSlider sliderMarineOxygen;
    private javax.swing.JSpinner spinnerMarineAmmo;
    private javax.swing.JSpinner spinnerMarineSoldier;
    private javax.swing.JTextArea txtAreaMarine;
    private javax.swing.JTextField txtFieldMarine;
    // End of variables declaration//GEN-END:variables

    @Override
    public void areaClear(boolean b) {
        if(b==true){
            lblMarineArea.setText("Area Cleared");
            txtAreaMarine.setText("");
            txtFieldMarine.setText("");
            spinnerMarineAmmo.setValue(0);
            spinnerMarineSoldier.setValue(0);
            sliderMarineEnergy.setValue(0);
            sliderMarineOxygen.setValue(0);
            chkBoxMarinePosition.setSelected(false);
        }else {
            lblMarineArea.setText("Area Not Cleared");
        }
    }

    @Override
    public void sendMessage(String sendMessage,int index,boolean position) {
        if(index==0) {
            txtAreaMarine.append(sendMessage+"\n");
        }else if(index==3 && position==true) {
            txtAreaMarine.append("Private : "+sendMessage+"\n");
        }
    }

    @Override
    public void position(Strength strength) {
        this.strength = strength;
        if(chkBoxMarinePosition.isSelected()) {
            switch(strength) {
                case LOW:
                    btnMarineShoot.setEnabled(false);
                    btnMarineSonar.setEnabled(false);
                    btnMarineTomahawk.setEnabled(false);
                    btnMarineTrident.setEnabled(false);
                    break;
                case MEDIUM:
                    btnMarineShoot.setEnabled(true);
                    btnMarineSonar.setEnabled(false);
                    btnMarineTomahawk.setEnabled(false);
                    btnMarineTrident.setEnabled(false);
                    break;
                case HIGH:
                    btnMarineShoot.setEnabled(true);
                    btnMarineSonar.setEnabled(true);
                    btnMarineTomahawk.setEnabled(false);
                    btnMarineTrident.setEnabled(false);
                    break;
                case STRONG:
                    btnMarineShoot.setEnabled(true);
                    btnMarineSonar.setEnabled(true);
                    btnMarineTomahawk.setEnabled(true);
                    btnMarineTrident.setEnabled(false);
                    break;
                case CLOSED:
                    btnMarineShoot.setEnabled(true);
                    btnMarineSonar.setEnabled(true);
                    btnMarineTomahawk.setEnabled(true);
                    btnMarineTrident.setEnabled(true);
                    break;
            }
        }else {
            btnMarineShoot.setEnabled(false);
            btnMarineSonar.setEnabled(false);
            btnMarineTomahawk.setEnabled(false);
            btnMarineTrident.setEnabled(false);
        }
    }
}